### ISSUE TITLE
How'd you get into programming?

### ISSUE THREAD

**Issue by kentcdodds** [joeeames/ama#3]

**Comment by joeeames** [comment]
For the long version of the story, check out my Hello World podcast: http://wildermuth.com/hwpod/31_Joe_Eames

In my Junior year of high school I took 1 class a day at the local University. I took Computer Science 105 which was the intro to programming for tech majors. At the time I was playing a bunch of Dungeons and Dragons so I started coding up a dungeon master's assistant command line program in Pascal. That was where I developed my love for coding. 

I got my first job because I was working at a place doing low level tech stuff (cabling, etc) and another manager came to my manager asking to borrow one of his programmers. He couldn't spare anyone, but he knew I had taken some coding classes in high school so the other manager handed me the FoxPro books the Friday before Memorial Day and said "if you can do this when you come back, I can use you as a programmer." So I spent 72 hours reading until I was crosseyed.

That's the short version. The long version on the podcast includes a lot more details, including the period where I programmed on paper, and some other interesting stuff.
